---
# Dockerfile found in .tools/Dockerfile and auto-built by the Dockerhub
image: "dduportal/cicd-gitpod"
# Multiple projects are expected, so we specify the "base directory" (e.g. "/workspace")
workspaceLocation: "."
...
